### ISSUE TITLE
`os.proc(..).call(..).err.text()` is always empty

### ISSUE THREAD

**Issue by davesmith00000** [com-lihaoyi/os-lib#138]
This example from the README doesn't work for me:

```
// Though you can avoid throwing by setting `check = false`
val fail = os.proc('ls, "doesnt-exist").call(cwd = wd, check = false) // Ok
assert(fail.exitCode != 0)                                            // Ok
fail.out.text() ==> ""                                                // Ok
assert(fail.err.text().contains("No such file or directory"))         // Fails.
```

`fail.err.text()` is consistently empty. I have tried it with other process calls too.

~~I've asked on Discord in case anyone has any bright ideas. Will update here if I get an answer.~~

---

Update: @lolgab has shown me that it works with this modification:
```
val fail = os.proc('ls, "doesnt-exist").call(cwd = wd, check = false, stderr = os.Pipe) // Ok
```

**Comment by lihaoyi** [comment]
This is intended behavior, unfortunately. By default, `stderr = os.Inherit, stdout = os.Pipe`. This inconsistency is because we assume `stderr` is normally intended for human consumption, while `stdout` is often not.

IME whatever we set the defaults to, there'll always be some confusion, so we'll probably leave this as is.
